/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooppro;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Amad khan
 */
public class Atm_pin extends javax.swing.JFrame {
    int counter =0;
   public static int pin;
   public static void setpin(int n){
       pin=n;
   }
   public static int getpin(){
       return pin;
   }

    /**
     * Creates new form Atm_pin
     */
    public Atm_pin() {
        setUndecorated(true);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tf4 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Enterbu = new javax.swing.JButton();
        Tf3 = new javax.swing.JTextField();
        but1 = new javax.swing.JButton();
        lab5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        Tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf4ActionPerformed(evt);
            }
        });
        jPanel1.add(Tf4);
        Tf4.setBounds(200, 240, 240, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooppro/logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 130, 60);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setText("Wellcome to ATM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 100, 170, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel4.setText("Pease Enter your 4-Digit Personal Identification Number(PIN)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 160, 530, 40);

        Enterbu.setBackground(new java.awt.Color(0, 102, 255));
        Enterbu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        Enterbu.setForeground(new java.awt.Color(255, 255, 255));
        Enterbu.setText("ENTER");
        Enterbu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterbuMouseClicked(evt);
            }
        });
        jPanel1.add(Enterbu);
        Enterbu.setBounds(280, 290, 80, 40);

        Tf3.setEditable(false);
        Tf3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jPanel1.add(Tf3);
        Tf3.setBounds(240, 100, 310, 40);

        but1.setBackground(new java.awt.Color(255, 0, 0));
        but1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        but1.setForeground(new java.awt.Color(255, 255, 255));
        but1.setText("X");
        but1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but1MouseClicked(evt);
            }
        });
        jPanel1.add(but1);
        but1.setBounds(590, 0, 50, 25);

        lab5.setBackground(new java.awt.Color(255, 51, 0));
        lab5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.add(lab5);
        lab5.setBounds(200, 210, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooppro/Atm pin.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 643, 432));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf4ActionPerformed

    private void but1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Thanks for using our Service");
        System.exit(0);

    }//GEN-LAST:event_but1MouseClicked

    private void EnterbuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterbuMouseClicked
        // TODO add your handling code here:
        
        
        boolean valid=false;
        Atm_menu g1=new Atm_menu();
        int pin=0;
        try{
         pin=Integer.parseInt(this.Tf4.getText());
         Atm_pin.setpin(pin);
         valid=true;
         
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(this, "Enter number 1234 Like that",
                    "Error", JOptionPane.ERROR_MESSAGE);
      
        }
        
        
            
             
             
           

        
        while(valid && counter <4){
                         
             valid=Bank.pincode(pin);
             if(!valid){
                 
                this.setVisible(true);
                this.lab5.setText("PLEASE ENTER CORRECT PIN");
                counter =counter +1;
                
            }
            else{
                
        
        g1.setVisible(true);
        g1.pack();
        g1.setLocationRelativeTo(null);
        g1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        break;
        
            }
         }
        if(counter==4){
            
            this.dispose();
        }
    }//GEN-LAST:event_EnterbuMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enterbu;
    public javax.swing.JTextField Tf3;
    private javax.swing.JPasswordField Tf4;
    private javax.swing.JButton but1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab5;
    // End of variables declaration//GEN-END:variables
}
